### ISSUE TITLE
Format on save causing Nova 6.2 to jump to start of file

### ISSUE THREAD

**Issue by craiga** [Aeron/Black.novaextension#2]
In Nova 6.2, saving a Python file with "Format a file on save" checked causes the editor to jump to the top of the file once Black has done formatting.

When working with moderately long files, you then lose your place and need to scroll back down to find your place.

Outside of this, I love having this extension. Thanks so much for providing it!

**Comment by Aeron** [comment]
Oh boy, it looks like this version did bring something unexpected. Maybe I overlooked something in the changelog after all. 

Thank you. I’ll certainly look into it, but I doubt there’s something I can do here, except for a temporary workaround since the extension doesn’t manipulate a cursor position in any way at this point. And did work properly for the previous five versions 😅

By the way, do you have other (my) extensions installed, like isort or mypy? Maybe it’s intertwined somehow, like with #1.

And yeah, you’re very welcome; I’m glad you’re using it 😊

**Comment by craiga** [comment]
I don't have any of your other extensions installed (I think I ran into that issue), but I've got https://github.com/alexanderweiss/nova-prettier set up and that seems to be working fine. I don't know if there's any possible interaction going on, or if there's a technique from that extension which could be adapted for this one?

**Comment by Aeron** [comment]
Ok, got it, thanks. I’ll check it out.

**Comment by craiga** [comment]
Looks like this has been fixed in [Nova 7](https://nova.app/releases/#v7)!

> Improved the ability to maintain cursor positions when an extension modifies the entire document
